StockMarketManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StockMarketManagement.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

StockMarketManagement/Controllers/LoginAuthController.cs
using StockMarketManagement.Models.DbContext;
using StockMarketManagement.Models.ViewModel;
using StockMarketManagement.Session;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StockMarketManagement.Controllers
{
    public class LoginAuthController : Controller
    {
        StockMarketEntities _opetion = new StockMarketEntities();
        public ActionResult Login()
        {
            return View();
        } 
        [HttpPost]
        public ActionResult Login(LoginModel db)
        {
            var userlist = _opetion.UserTable.FirstOrDefault(m => m.Email == db.Email);
            if (ModelState.IsValid && userlist.Email == db.Email && userlist.Password == db.Password)
            {
                SessionHelper.LoggedInUser = userlist.Username;
                SessionHelper.GetUserId = userlist.Userid;
                Session["Username"] = SessionHelper.LoggedInUser;
                return RedirectToAction("Index", "StockMarket");
            }
            else
            {
                return View(db);
            }
        }
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(UserModel db)
        {
            var IsemailExist = _opetion.UserTable.Any(m => m.Email == db.Email);
            if (ModelState.IsValid && !IsemailExist)
            {

                SqlParameter[] registeruser = new SqlParameter[]
                {
                    new SqlParameter("@username",db.Username),
                    new SqlParameter("@email",db.Email),
                    new SqlParameter("@passward",db.Password)                   
                };

                _opetion.Database.SqlQuery<UserModel>("Exec RegisterUser @username,@email,@passward", registeruser).ToList();
                return RedirectToAction("Login");
            }
            return View();
        }
        public ActionResult Logout()
        {
            try
            {
                SessionHelper.Logout();
                
                return RedirectToAction("Login");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

StockMarketManagement/Controllers/StockMarketController.cs
using StockMarketManagement.Common;
using StockMarketManagement.Models.DbContext;
using StockMarketManagement.Models.ViewModel;
using StockMarketManagement.Repository.Services;
using StockMarketManagement.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace StockMarketManagement.Controllers
{
    public class StockMarketController : Controller
    {
        StockMarketEntities _DbContext = new StockMarketEntities();
        StockList service = new StockList();
        public async Task<ActionResult> Index()
        {
            List<StockDetails> listOfstoc = new List<StockDetails>();

           var list = service.GetStockDetails(1);
            for(int i = 0; i < list.Count; i++)
            {
            StockDetails stockDetails = new StockDetails();
               var listobj = await WebApi.StockDetails(list[i].SYMBOL);

                stockDetails.SYMBOL = list[i].SYMBOL;
                stockDetails.price = listobj.price;
                stockDetails.BuyingPrice = list[i].BuyingPrice;
                stockDetails.Quntity = list[i].Quntity;               
                listOfstoc.Add(stockDetails);
            }
           return View(listOfstoc);
        }

        public ActionResult AddStock()
        {

            ViewBag.list = service.GetStockList();
            return View();
        }


        [HttpPost]
        public ActionResult AddStock(EQUITYModel db)
        {
            if (ModelState.IsValid)
            {
                    db.Userid = SessionHelper.GetUserId;
                if (service.AddStocks(db) == 1)
                {
                    Session["Symbol"] = db.SYMBOL;
                    return RedirectToAction("Index");
                }
            }
            return View(db);
        }

    }
}

StockMarketManagement/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

StockMarketManagement/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

StockMarketManagement/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

StockMarketManagement/Views/LoginAuth/Login.cshtml
@model StockMarketManagement.Models.ViewModel.LoginModel
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<link href="~/Content/toastr.min.css" rel="stylesheet" />
<script src="~/Scripts/toastr.min.js"></script>
@if (TempData["loginfaild"] != null)
{
<script>
    toastr.error('@TempData["loginfaild"]')
</script>}
<!doctype html>
<html lang="en">
<head>

    <title>Login 07</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet">

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Content/Theme/Login/css/style.css">

    <script src="~/Scripts/toastr.min.js"></script>
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
</head>

<body>

    @if (TempData["Loginfail"] != null)
    {
<script>
                toastr.error('@TempData["Loginfail"]')
</script>}
    @if (TempData["register"] != null)
    {
<script>
                  toastr.success('@TempData["register"]')
</script>}
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Login </h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-10">
                    <div class="wrap d-md-flex">
                        <div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
                            <div class="text w-100">
                                <h2>Welcome to login</h2>
                                <p>Don't have an account?</p>
                                @Html.ActionLink("Sign Up", "Register", "LoginAuth", null, new { @class = "btn btn-white btn-outline-white" })

                            </div>
                        </div>
                        <div class="login-wrap p-4 p-lg-5">
                            <div class="d-flex">
                                <div class="w-100">
                                    <h3 class="mb-4">Sign In</h3>
                                </div>

                            </div>
                            <form method="post" class="signin-form">
                                <div class="form-group mb-3">
                                    <label class="label" for="email">Email</label>
                                    <input type="text" class="form-control" placeholder="Email" name="Email" value="@(Model != null && Model.Email !=null ? Model.Email:"")">
                                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group mb-3">
                                    <label class="label" for="password">Password</label>
                                    <input type="password" class="form-control" placeholder="Password" name="Password" value="@(Model != null && Model.Password !=null ? Model.Password:"")">
                                    @Html.ValidationMessageFor(m=>m.Password, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
                                </div>
                                <div class="form-group d-md-flex">
                                    <div class="w-50 text-left">
                                        <label class="checkbox-wrap checkbox-primary mb-0">
                                            Remember Me
                                            <input type="checkbox" checked>
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    <div class="w-50 text-md-right">
                                        <a href="#">Forgot Password</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/Content/Theme/Login/js/jquery.min.js"></script>
    <script src="~/Content/Theme/Login/js/popper.js"></script>
    <script src="~/Content/Theme/Login/js/bootstrap.min.js"></script>
    <script src="~/Content/Theme/Login/js/main.js"></script>

</body>
</html>

StockMarketManagement/Views/LoginAuth/Register.cshtml
@model StockMarketManagement.Models.ViewModel.UserModel
<!doctype html>
<html lang="en">
<head>
    <title>Login 07</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="~/Content/Theme/Login/css/style.css">
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/toastr.min.js"></script>
    <link href="~/Content/toastr.min.css" rel="stylesheet" />
</head>
<body>
    @if (TempData["Registerfail"] != null)
    {
<script>
                    toastr.error('@TempData["Registerfail"]')
</script>
}
    @if (TempData["faieldRegister"] != null)
    {
<script>
                    toastr.error('@TempData["faieldRegister"]')
</script>
}
    <section class="ftco-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-6 text-center mb-5">
                    <h2 class="heading-section">Register</h2>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-12 col-lg-10">
                    <div class="wrap d-md-flex">
                        <div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
                            <div class="text w-100">
                                <h2>Welcome to Register</h2>
                                <p>Do have an account?</p>
                                @Html.ActionLink("Sign In", "Login", "LoginAuth", null, new { @class = "btn btn-white btn-outline-white" })

                            </div>
                        </div>
                        <div class="login-wrap p-4 p-lg-5">
                            <div class="d-flex">
                                <div class="w-100">
                                    <h3 class="mb-4">Sign Up</h3>
                                </div>

                            </div>
                            <form method="post" class="signin-form" enctype="multipart/form-data">
                             
                                <div class="form-group mb-3">
                                    <label class="label" for="name">Name</label>
                                    <input type="text" class="form-control" placeholder="Name" name="UserName" value="@(Model != null && Model.Username !=null ? Model.Username:"")">
                                    @Html.ValidationMessageFor(m =>m.Username, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group mb-3">
                                    <label class="label" for="email">Email</label>
                                    <input type="text" class="form-control" placeholder="Email" name="Email" value="@(Model != null && Model.Email !=null ? Model.Email:"")">
                                    @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
                                </div>
                               
                                <div class="form-group mb-3">
                                    <label class="label" for="password">Password</label>
                                    <input type="password" class="form-control" placeholder="Password" name="Password" value="@(Model != null && Model.Password !=null ? Model.Password:"")">
                                    @Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group mb-3">
                                    <label class="label" for="conformpassword">conformpassword</label>
                                    <input type="password" class="form-control" placeholder="conformpassword" name="ConformPassword" value="@(Model != null && Model.ConformPassword !=null ? Model.ConformPassword:"")">
                                    @Html.ValidationMessageFor(m => m.ConformPassword, "", new { @class = "text-danger" })
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
                                </div>
                                <div class="form-group d-md-flex">
                                    <div class="w-50 text-left">
                                        <label class="checkbox-wrap checkbox-primary mb-0">
                                            Remember Me
                                            <input type="checkbox" checked>
                                            <span class="checkmark"></span>
                                        </label>

                                    </div>
                                    <div class="w-50 text-md-right">
                                        <a href="#">Forgot Password</a>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <script src="~/Content/Theme/Login/js/jquery.min.js"></script>
    <script src="~/Content/Theme/Login/js/popper.js"></script>
    <script src="~/Content/Theme/Login/js/bootstrap.min.js"></script>
    <script src="~/Content/Theme/Login/js/main.js"></script>

</body>
</html>

StockMarketManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>  
</head>
<body> 
    <div class="container-fluid body-content">
        @RenderBody()    
    </div>  
</body>
</html>

StockMarketManagement/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="~/Content/Theme/Dashboard/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Custom styles for this template-->
    <link href="~/Content/Theme/Dashboard/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="Index">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">


            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                   aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-play"></i>
                    <span>Add Stock</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="AddStock">Add Stock</a>
                    </div>
                </div>
            </li>

          


        </ul>
        <!-- End of Sidebar -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>



                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">



                        <!-- Nav Item - Alerts -->
                        <li class="nav-item dropdown no-arrow mx-1">

                            <!-- Dropdown - Alerts -->
                            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="alertsDropdown">
                                <h6 class="dropdown-header">
                                    Alerts Center
                                </h6>



                                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
                            </div>
                        </li>

                        <!-- Nav Item - Messages -->
                        <li class="nav-item dropdown no-arrow mx-1">

                            <!-- Dropdown - Messages -->
                            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="messagesDropdown">
                                <h6 class="dropdown-header">
                                    Message Center
                                </h6>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="img/undraw_profile_1.svg"
                                             alt="...">
                                        <div class="status-indicator bg-success"></div>
                                    </div>
                                    <div class="font-weight-bold">
                                        <div class="text-truncate">
                                            Hi there! I am wondering if you can help me with a
                                            problem I've been having.
                                        </div>
                                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="img/undraw_profile_2.svg"
                                             alt="...">
                                        <div class="status-indicator"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">
                                            I have the photos that you ordered last month, how
                                            would you like them sent to you?
                                        </div>
                                        <div class="small text-gray-500">Jae Chun · 1d</div>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="img/undraw_profile_3.svg"
                                             alt="...">
                                        <div class="status-indicator bg-warning"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">
                                            Last month's report looks great, I am very happy with
                                            the progress so far, keep up the good work!
                                        </div>
                                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                                    </div>
                                </a>
                                <a class="dropdown-item d-flex align-items-center" href="#">
                                    <div class="dropdown-list-image mr-3">
                                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                                             alt="...">
                                        <div class="status-indicator bg-success"></div>
                                    </div>
                                    <div>
                                        <div class="text-truncate">
                                            Am I a good boy? The reason I ask is because someone
                                            told me that people say this to all dogs, even if they aren't good...
                                        </div>
                                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                                    </div>
                                </a>
                                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">@Session["Username"]</span>
                                <img class="img-profile rounded-circle"
                                     src="~/Content/Theme/Dashboard/img/undraw_profile.svg">

                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">


                                @Html.ActionLink("LogOut", "Logout", "LoginAuth", null, new { @class = "ms-3 text-dark text-decoretion-none" })


                            </div>
                        </li>

                    </ul>

                </nav>
                <div>
                    @RenderBody()
                </div>
            </div>
        </div>

    </div>







    <!-- Bootstrap core JavaScript-->

    <script src="~/Content/Theme/Dashboard/vendor/jquery/jquery.min.js"></script>

    <script src="~/Content/Theme/Dashboard/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Content/Theme/Dashboard/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Content/Theme/Dashboard/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Content/Theme/Dashboard/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Content/Theme/Dashboard/js/demo/chart-area-demo.js"></script>
    <script src="~/Content/Theme/Dashboard/js/demo/chart-pie-demo.js"></script>

</body>

</html>

StockMarketManagement/Views/StockMarket/AddStock.cshtml
@model StockMarketManagement.Models.ViewModel.EQUITYModel

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stock Market</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">

</head>
<body>
    <div class="container mt-5">
        <form method="post" class="row">
            <div class="col-md-6 offset-md-3">
              
                <div class="mb-3">
                    <select class="form-select" aria-label="Default select example" name="SYMBOL">
                        <option selected>Select Your Stock</option>
                        @if (ViewBag.list != null)
                        {
                            foreach (var item in ViewBag.list)
                            {
                                <option value="@item.SYMBOL">@item.SYMBOL</option>
                            }
                        }
                    </select>
                </div>
                <div class="mb-3">
                    <label for="inputField" class="form-label">Enter Quntity</label>
                    <input type="number" class="form-control" name="Quntity" placeholder="Enter Your Counity">
                </div>
                <div class="mb-3">
                    <label for="inputField" class="form-label">Buying Price</label>
                    <input type="number" class="form-control" name="BuyingPrice" step="0.01" placeholder="Enter Your Buying Price">
                </div>
                <div class="mx-auto">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
            </div>
           
        </form>
    </div>

    <!-- Bootstrap JS Bundle (optional) -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
</body>
</html>